### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Mikeost** [MikeostCorp/Math-Algorithms#7]
TODO list:
- [ ] Write unit tests for each module
- [ ] Build a CI/CD pipeline(Github Actions)
- [ ] In Fibonacci function rewrite recursion to loop
